services:
  nestapp:
    container_name: 'nestapp'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=ki8vi
      - DB_PASSWORD=rs12345
      - DB_NAME=library
    depends_on:
      - db

  db:
    container_name: 'db'
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
